
class Consts:
    SCREEN_TITLE = "Magic of Roz"

    SPRITE_IMAGE_SIZE = 128
    SPRITE_SCALING_PLAYER = 0.5
    SPRITE_SCALING_TILES = 0.5
    
    SPRITE_SIZE = int(SPRITE_IMAGE_SIZE * SPRITE_SCALING_TILES)
    
    SCREEN_GRID_WIDTH = 25
    SCREEN_GRID_HEIGHT = 15
    
    SCREEN_WIDTH = SPRITE_SIZE * SCREEN_GRID_WIDTH
    SCREEN_HEIGHT = SPRITE_SIZE * SCREEN_GRID_HEIGHT
    
    RIGHT_FACING = 0
    LEFT_FACING = 1
    
    PLAYER_START_X = 2 
    PLAYER_START_Y = 10
    
    PLAYER_MOVEMENT_SPEED = 10
    
